require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/LineLength:
  Enabled: true
  Max: 120

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  CountAsOne: ['array', 'heredoc', 'method_call']

Metrics/ClassLength:
  Enabled: true
  CountAsOne: ['array', 'heredoc', 'method_call']

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  CountAsOne: ['array', 'heredoc', 'method_call']
  Max: 20

Metrics/ModuleLength:
  Enabled: true
  CountAsOne: ['array', 'heredoc', 'method_call']

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
