#!/usr/bin/env ruby
# frozen_string_literal: true

debug = true if ARGV.delete("-d")
debug = true if ARGV.delete("--debug")
ENV["ATLASQ_DEBUG"] = "1" if debug

# Avoid warnings on Ruby 2.7 related to pattern matching.
Warning[:experimental] = false

$LOAD_PATH.unshift File.expand_path("../lib", __dir__)
require "atlasq"

Atlasq::Shell.start!
