name: CI
on:
  push:
    branches: main
  pull_request:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@main

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - name: Outdated readme check
      run: bundle exec rake readme:outdated

    - name: Outdated cache check
      run: bundle exec rake cache:outdated
  tests:
    needs: docs
    strategy:
      matrix:
        platform: ["ubuntu-latest", "macos-latest"]
        ruby: [3.0, 3.1, 3.2, 3.3]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up Git repository
      uses: actions/checkout@main

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run linter
      run: bundle exec rake lint

    - name: Run tests
      run: bundle exec rake test
